### ISSUE TITLE
Deprecated argument warning

### ISSUE THREAD

**Issue by holatodos** [clouddrove/terraform-aws-ec2-autoscaling#8]
Terraform v1.2.2. with AWS provider 4.14.0 and module version 1.0.1 issues the following warning.

│ Warning: Argument is deprecated
│ 
│   with module.ec2-autoscaling.aws_autoscaling_group.on_demand,
│   on .terraform/modules/ec2-autoscaling/main.tf line 181, in resource "aws_autoscaling_group" "on_demand":
│  181:   tags = flatten([
│  182:     for key in keys(module.labels.tags) :
│  183:     {
│  184:       key                 = key
│  185:       value               = module.labels.tags[key]
│  186:       propagate_at_launch = true
│  187:     }
│  188:   ])
│ 
│ Use tag instead
│ 
│ (and one more similar warning elsewhere)

**Comment by yadavprakash** [comment]
@holatodos I have fixed deprecated tags please use latest code.
